# Generated by Django 5.1.4 on 2025-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit margin percentage (e.g., 15.00 for 15%)', max_digits=5),
        ),
    ]
