# Generated by Django 5.2.7 on 2025-11-24 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_apilog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this API key (e.g., 'Production Site', 'Testing')", max_length=100)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars for identification', max_length=20)),
                ('can_purchase', models.BooleanField(default=True, help_text='Can purchase phone numbers')),
                ('can_check_balance', models.BooleanField(default=True, help_text='Can check account balance')),
                ('can_get_prices', models.BooleanField(default=True, help_text='Can get pricing information')),
                ('can_cancel', models.BooleanField(default=True, help_text='Can cancel orders')),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Max API calls per minute')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Markup percentage added to base price (e.g., 10.00 for 10%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIOrderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('api_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('markup_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.apikey')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rental')),
            ],
            options={
                'verbose_name': 'API Order',
                'verbose_name_plural': 'API Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Your webhook endpoint URL')),
                ('secret', models.CharField(help_text='Webhook secret for signature verification', max_length=64)),
                ('on_sms_received', models.BooleanField(default=True)),
                ('on_order_expired', models.BooleanField(default=True)),
                ('on_order_cancelled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Webhook',
                'verbose_name_plural': 'API Webhooks',
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.apikey')),
            ],
            options={
                'verbose_name': 'API Request',
                'verbose_name_plural': 'API Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', '-created_at'], name='app_apirequ_api_key_ca4ed9_idx'), models.Index(fields=['endpoint', '-created_at'], name='app_apirequ_endpoin_5805d3_idx')],
            },
        ),
    ]
