# Generated by Django 5.2.7 on 2026-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_apikey_apiordermapping_apiwebhook_apirequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mtelsms_service_id',
            field=models.CharField(blank=True, help_text='MTelSMS service ID (numeric) for API calls', max_length=50, null=True),
        ),
    ]
