# Generated by Django 5.1.4 on 2025-07-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_rental_max_price_alter_rental_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit margin in Naira (e.g., 100.00 for ₦100)', max_digits=12),
        ),
    ]
