# Generated by Django 5.1.4 on 2025-08-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_update_profit_margin_to_naira'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
