# Generated by Django 5.1.4 on 2025-08-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rental_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
    ]
