# Generated by Django 5.1.4 on 2025-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_userprofile_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_ltr',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='paid_until',
        ),
        migrations.RemoveField(
            model_name='service',
            name='daily_price',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('RENTAL', 'Rental Payment'), ('REFUND', 'Refund'), ('PENALTY', 'Penalty')], max_length=20),
        ),
    ]
