# Generated by Django 5.1.4 on 2025-08-19 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_ltr_and_daily_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveSimAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='JWT token from 5sim.net', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='5sim account balance', max_digits=12)),
                ('rating', models.IntegerField(default=96, help_text='5sim account rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_balance_check', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiveSimOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(unique=True)),
                ('order_type', models.CharField(choices=[('ACTIVATION', 'Activation'), ('HOSTING', 'Hosting'), ('REUSE', 'Reuse')], default='ACTIVATION', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_naira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'SMS Received'), ('CANCELED', 'Canceled'), ('TIMEOUT', 'Timeout'), ('FINISHED', 'Finished'), ('BANNED', 'Number Banned')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('forwarding', models.BooleanField(default=False)),
                ('forwarding_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reuse_enabled', models.BooleanField(default=False)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('referral_key', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiveSimSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.BigIntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='app.fivesimorder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
