# Generated by Django 5.1.4 on 2025-08-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fivesimapikey_fivesimorder_fivesimsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS Service Category',
                'verbose_name_plural': 'SMS Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=50, unique=True)),
                ('service_name', models.CharField(max_length=100)),
                ('base_price_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('price_update_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.smsservicecategory')),
            ],
            options={
                'verbose_name': 'SMS Service',
                'verbose_name_plural': 'SMS Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='SMSOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=100)),
                ('operator_code', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=100)),
                ('base_price_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('profit_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_count', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='app.smsservice')),
            ],
            options={
                'verbose_name': 'SMS Operator',
                'verbose_name_plural': 'SMS Operators',
                'ordering': ['country_name', 'operator_name'],
                'unique_together': {('country_code', 'operator_code', 'service')},
            },
        ),
    ]
