# Generated by Django 5.1.4 on 2025-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_smsservicecategory_smsservice_smsoperator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsoperator',
            name='profit_margin_percent',
        ),
        migrations.RemoveField(
            model_name='smsservice',
            name='profit_margin_percent',
        ),
        migrations.AddField(
            model_name='smsoperator',
            name='base_price_naira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='smsoperator',
            name='profit_margin_naira',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='smsservice',
            name='base_price_naira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='smsservice',
            name='profit_margin_naira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
