# Generated by Django 5.1.4 on 2025-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_smsoperator_profit_margin_percent_and_more'),
    ]

    operations = [
        # Add new Naira-based fields to SMSService
        migrations.AddField(
            model_name='smsservice',
            name='base_price_naira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='smsservice',
            name='profit_margin_naira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
