# Generated by Django 5.1.4 on 2025-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250819_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsservice',
            name='base_price_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
