# Generated by Django 5.1.4 on 2025-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_smsservice_base_price_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fivesimorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'SMS Received'), ('CANCELED', 'Canceled'), ('TIMEOUT', 'Timeout'), ('FINISHED', 'Finished'), ('BANNED', 'Number Banned'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
